'use client';

import { useCallback } from 'react';
import Link from 'next/link';
import { useReadingProgressAndShareBar } from '@/components/useReadingProgressAndShareBar';

// Generated by the dashboard publish framework from a markdown upload. Edit the copy freely; the
// generator only ever creates a new file and never overwrites an existing post.
export default function NewsletterEverstoneWingifyBootstrappedBuyout400500mPlatform() {
  useReadingProgressAndShareBar();

  const shareTwitter = useCallback(() => {
    const url = encodeURIComponent(window.location.href);
    const text = encodeURIComponent("Everstone and Wingify: $200M Bootstrapped Buyout to $400–500M Platform, via @microsearchfund");
    window.open(`https://twitter.com/intent/tweet?url=${url}&text=${text}`, '_blank');
  }, []);

  const shareLinkedIn = useCallback(() => {
    const url = encodeURIComponent(window.location.href);
    window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${url}`, '_blank');
  }, []);

  const shareEmail = useCallback(() => {
    const subject = encodeURIComponent("Everstone and Wingify: $200M Bootstrapped Buyout to $400–500M Platform");
    const body = encodeURIComponent(`Thought you'd find this useful: ${window.location.href}`);
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  }, []);

  const copyLink = useCallback((btn: HTMLButtonElement) => {
    navigator.clipboard.writeText(window.location.href).then(() => {
      btn.classList.add('copied');
      const tooltip = btn.querySelector('.tooltip');
      if (tooltip) tooltip.textContent = 'Copied!';
      setTimeout(() => {
        btn.classList.remove('copied');
        if (tooltip) tooltip.textContent = 'Copy link';
      }, 2000);
    });
  }, []);

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: `
        .blog-author-byline {
          font-family: var(--font-lora), 'Lora', serif;
          font-size: 13px;
          color: var(--text-muted);
          margin-top: 14px;
          margin-bottom: 0;
        }
        .blog-author-byline a {
          color: var(--gold);
          text-decoration: none;
          border-bottom: 1px solid transparent;
          transition: border-color 0.2s;
        }
        .blog-author-byline a:hover { border-bottom-color: var(--gold); }

        .currency-note {
          font-family: var(--font-lora), 'Lora', serif;
          font-size: 12px;
          font-style: italic;
          color: var(--text-muted);
          margin: 14px 0 0;
          line-height: 1.7;
        }

        .deal-table-wrap {
          margin: 32px 0;
          border: 1px solid var(--border);
          border-radius: 3px;
          overflow-x: auto;
        }
        .deal-table {
          width: 100%;
          border-collapse: collapse;
          font-family: var(--font-lora), 'Lora', serif;
          font-size: 13.5px;
        }
        .deal-table th {
          text-align: left;
          font-size: 10px;
          letter-spacing: 2px;
          text-transform: uppercase;
          color: var(--gold);
          padding: 12px 18px;
          border-bottom: 1px solid var(--border);
          background: rgba(255,255,255,0.02);
        }
        .deal-table td {
          padding: 12px 18px;
          border-bottom: 1px solid var(--border);
          color: var(--text-secondary);
          line-height: 1.6;
          vertical-align: top;
        }
        .deal-table tr:last-child td { border-bottom: none; }
        .deal-table td:first-child {
          color: var(--text-primary);
          font-weight: 500;
          white-space: nowrap;
        }

        .blog-faq {
          margin-top: 64px;
          padding-top: 48px;
          border-top: 1px solid var(--border);
        }
        .blog-faq-item {
          border-bottom: 1px solid var(--border);
          padding: 22px 0;
        }
        .blog-faq-q {
          font-family: var(--font-cormorant), 'Cormorant', serif;
          font-size: 20px;
          font-weight: 500;
          color: var(--text-primary);
          line-height: 1.35;
          margin-bottom: 10px;
        }
        .blog-faq-a {
          font-family: var(--font-lora), 'Lora', serif;
          font-size: 14px;
          color: var(--text-secondary);
          line-height: 1.9;
          margin: 0;
        }

        .sources-appendix {
          margin-top: 56px;
          padding-top: 32px;
          border-top: 1px solid var(--border);
        }
        .sources-appendix h3 {
          font-family: var(--font-cormorant), 'Cormorant', serif;
          font-size: 15px;
          letter-spacing: 1px;
          color: var(--text-primary);
          margin: 24px 0 8px;
        }
        .sources-appendix p,
        .sources-appendix li {
          font-family: var(--font-lora), 'Lora', serif;
          font-size: 12.5px;
          color: var(--text-muted);
          line-height: 1.8;
        }
        .sources-appendix ul { margin: 0 0 16px; padding-left: 18px; }

        .story-coda .coda-link {
          display: inline-block;
          margin-top: 24px;
          font-size: 10px;
          letter-spacing: 5px;
          text-transform: uppercase;
          color: var(--canvas);
          background: var(--gold);
          padding: 13px 30px;
          border-radius: 2px;
          text-decoration: none;
          transition: opacity 0.2s;
        }
        .story-coda .coda-link:hover { opacity: 0.88; }
        .story-coda .coda-link.secondary {
          background: transparent;
          border: 1px solid var(--gold-dim);
          color: var(--gold);
          margin-left: 12px;
        }

        @media (max-width: 640px) {
          .story-coda .coda-link.secondary { margin-left: 0; margin-top: 12px; }
        }
      ` }} />

      <div className="reading-progress" id="readingProgress" />

      <div className="share-bar" id="shareBar">
        <button className="share-btn" onClick={shareTwitter} aria-label="Share on Twitter">
          <svg viewBox="0 0 24 24"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" /></svg>
          <span className="tooltip">Twitter / X</span>
        </button>
        <button className="share-btn" onClick={shareLinkedIn} aria-label="Share on LinkedIn">
          <svg viewBox="0 0 24 24"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 01-2.063-2.065 2.064 2.064 0 112.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" /></svg>
          <span className="tooltip">LinkedIn</span>
        </button>
        <button className="share-btn" onClick={(e) => copyLink(e.currentTarget)} aria-label="Copy link">
          <svg viewBox="0 0 24 24"><path d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" /></svg>
          <span className="tooltip">Copy link</span>
        </button>
        <button className="share-btn" onClick={shareEmail} aria-label="Share via email">
          <svg viewBox="0 0 24 24"><path d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" /></svg>
          <span className="tooltip">Email</span>
        </button>
      </div>

      <div className="story-hero" id="storyStart">
        <Link href="/newsletter" className="back-link">← Kautilya Newsletter</Link>
        <div className="meta-row">
          <span className="meta-tag">Deal Teardown</span>
          <span className="meta-tag">Indian SaaS &amp; Private Equity</span>
          <span className="meta-tag">13 min read</span>
        </div>
        <h1>Everstone and Wingify: $200M Bootstrapped Buyout to $400–500M Platform</h1>
        <p className="blog-author-byline">By <a href="/team">Kautilya PE</a>&nbsp;&nbsp;·&nbsp;&nbsp;30 September 2026</p>
        <div className="hero-line" />
      </div>

      <article className="story-body">

<p><strong>Everstone paid about $200M in cash for 80% of Wingify, a Delhi software company its founder had built for 15 years without a rupee of outside money. Then it did what the founder never had: within twelve months it bought a startup, merged Wingify with a Paris rival, and pumped in $150M, turning a $200M buyout into a platform worth $400 to 500M.</strong></p>
<div className="pull-quote">
<p>Wingify makes VWO, a tool that helps websites test and improve how they sell, and it reached $50M of annual recurring revenue with 6,000 clients while staying entirely bootstrapped. <strong>Everstone bought 80% for roughly $200M, about four times revenue, giving founder Paras Chopra a rare full cash exit while he kept 10.45% and a board seat.</strong> What makes this deal matter is not the price. It is what came next: a buy-and-build sprint no bootstrapped founder would run, because it takes capital and risk appetite a self-funded company deliberately avoids. Everstone used Wingify as a platform, bolted on an AI startup, merged in France&apos;s AB Tasty to clear $100M of combined revenue, and led a $150M rights issue to fund it. The founder got liquidity; the buyer got a global challenger it assembled in a year.</p>
</div>
<ul className="constraint-list">
<li><strong>The setup.</strong> The deal was announced in January 2025, an all-cash buyout at roughly $200M. Chopra, who had held 71%, sold most of it; after dilution Everstone holds 76.84%, Chopra 10.45%, CEO Sparsh Gupta 4.86%. Leadership kept meaningful equity and, unusually for a PE buyout, there were no layoffs and no cost-cutting.<ul className="constraint-list">
<li>In plain terms, a bootstrapped company: one built without venture capital or any outside investment, funded entirely by its own revenue. That makes it profitable and independent, but also cautious, because every rupee of growth has to be self-financed rather than raised.</li>
</ul></li>
<li><strong>The move.</strong> Everstone treated the buyout as a starting point. In December 2025 Wingify made the first acquisition in its history, an AI startup called Blitzllama. In January 2026 it merged with AB Tasty of Paris, buying out that company&apos;s venture backers, to reach over $100M of combined revenue. In April 2026 a ₹ 1,381 Cr ($150M) rights issue, led by Everstone, funded it all.</li>
<li><strong>The point.</strong> Two lessons in one deal. For strategy: a bootstrapped company and a PE owner want opposite things, safety versus scale, and the buyout converts a cautious, profitable asset into an aggressive growth platform. For deal-making: the way to keep a founder-built company intact is to keep the people, and Everstone bought 80% while leaving the CEO, the equity and the culture in place.</li>
</ul>

<div className="key-takeaways">
<div className="phase-label">Key Takeaways</div>
<ul><li>Everstone paid roughly $200M in cash for 80% of Wingify (VWO), about 4x its $50M of annual recurring revenue. The price is press-reported and founder-confirmed, not filed.</li>
<li>Within a year Wingify bought Blitzllama, merged with AB Tasty to pass $100M of combined revenue, and raised a ₹ 1,381 Cr ($150M) rights issue led by Everstone.</li>
<li>The founder took a rare cash exit but kept 10.45% and a board seat, and the CEO and leadership kept meaningful equity.</li>
<li>The rights issue is the signal to watch: fresh primary capital soon after buying shows a sponsor committing to the growth plan.</li>
<li>FY25 shows the cost of the push: revenue up 34%, net profit down over 60%, expenses up 70%.</li></ul>
</div>

<h2>The deal at a glance</h2>
<div className="deal-table-wrap">
<table className="deal-table">
<thead><tr><th><strong>~$200M</strong></th><th><strong>80%</strong></th><th><strong>$400–500M</strong></th><th><strong>15 yrs</strong></th></tr></thead>
<tbody>
<tr><td>BUYOUT VALUE, ~4x REVENUE</td><td>STAKE EVERSTONE ACQUIRED</td><td>PLATFORM VALUE, 12 MONTHS ON</td><td>BOOTSTRAPPED, ZERO OUTSIDE CAPITAL</td></tr>
</tbody>
</table>
</div>
<p><em>The founder&apos;s exit in one line: Paras Chopra went from 71% to 10.45% and a board seat, cashing out most of what he built. Sources: RoC filing, TechCrunch.</em></p>
<h2>Deal Radar</h2>
<h3>The numbers</h3>
<div className="deal-table-wrap">
<table className="deal-table">
<thead><tr><th><strong>Indicator</strong></th><th><strong>Figure</strong></th></tr></thead>
<tbody>
<tr><td><strong>Buyer</strong></td><td>Everstone Capital, Singapore PE with AUM over $8B, via the SPV Everdoc Pte. Ltd. MD Sandeep Singh</td></tr>
<tr><td><strong>Target</strong></td><td>Wingify Software, New Delhi. Flagship VWO: A/B testing, heatmaps, session recordings, experimentation SaaS. Founded 2010, unlisted</td></tr>
<tr><td><strong>Seller</strong></td><td>Paras Chopra, co-founder, who held 71%; plus minority holders. He keeps 10.45% and a board seat, no operating role</td></tr>
<tr><td><strong>Deal value</strong></td><td>~$200M, all cash, for 80% (press-reported and confirmed by the founder, not in official filings). About 4x the $50M revenue</td></tr>
<tr><td><strong>Post-deal cap table</strong></td><td>Everstone 76.84%, Chopra 10.45%, Vyom Mankekar 5.07%, CEO Sparsh Gupta 4.86%, per the March 2025 RoC filing</td></tr>
<tr><td><strong>The business</strong></td><td>$50M ARR, 6,000+ clients across 90 countries, ~90% of revenue from the US and Europe. Clients include Disney, Decathlon, UNICEF</td></tr>
<tr><td><strong>Bolt-on</strong></td><td>December 2025: Wingify buys Blitzllama, an AI user-research startup, all cash. The first acquisition in the company&apos;s history</td></tr>
<tr><td><strong>The merger</strong></td><td>January 2026: merged with AB Tasty of Paris. Combined ARR over $100M, 4,000+ customers, ~800 staff, valued at $400–500M</td></tr>
<tr><td><strong>The cleanup</strong></td><td>Everstone bought out AB Tasty&apos;s venture backers, Credit Mutuel Equity and Partech. Their co-founders keep voting rights but gave up board seats</td></tr>
<tr><td><strong>The fuel</strong></td><td>April 2026: a ₹ 1,381 Cr ($150M) rights issue, Everstone leading with ₹ 1,250 Cr. 16,08,199 shares at ₹ 8,590</td></tr>
<tr><td><strong>FY25 financials</strong></td><td>Revenue ₹ 386 Cr (+34%); net profit ₹ 24 Cr (down 60%+); expenses ₹ 376 Cr (+70%), employee costs up 88%. Growth over margin, by design</td></tr>
<tr><td><strong>Advisers</strong></td><td>AZB &amp; Partners for Everstone, Trilegal for the founders, DC Advisory as Wingify&apos;s exclusive financial adviser</td></tr>
<tr><td><strong>The field</strong></td><td>The combined entity now competes with Optimizely, Bloomreach and Adobe in enterprise experimentation and personalisation</td></tr>
<tr><td><strong>Status (Sep 16, 2026)</strong></td><td>Completed. Wingify and AB Tasty operate as one company under the Wingify brand, Sparsh Gupta CEO, headquartered in New Delhi</td></tr>
</tbody>
</table>
</div>
<p><em>Twelve months from a single buyout to a two-continent platform, funded by a mid-course capital raise. Sources: TechCrunch, Inc42, RoC filings.</em></p>
<h3>What actually happened. Delhi and Paris, 2025 to 2026</h3>
<ul className="constraint-list">
<li><strong>A founder took a rare full exit, and the buyer kept everything that worked.</strong> Chopra had built Wingify to $50M of revenue over fifteen years with no outside capital. Selling 80% for cash gave him the liquidity a bootstrapped founder can otherwise only get by staying forever, while he kept 10.45% and a board seat. Everstone kept the CEO, the equity incentives and the culture, running what the CEO called atypical PE: no layoffs, no cost-cutting.<ul className="constraint-list">
<li>Why that matters: the risk in buying a founder-built company is that the value walks out with the founder. Everstone managed that by making the exit partial in spirit, cash for the founder but continuity for everyone who runs the business day to day.</li>
</ul></li>
<li><strong>The buyer ran a playbook the company never could.</strong> A bootstrapped company grows only as fast as its own cash allows, which is why Wingify had never made an acquisition in fifteen years. Under Everstone it made two and a cross-border merger in twelve months. That is the point of the buyout: PE capital and risk appetite turn a cautious niche leader into a platform that consolidates its market.</li>
<li><strong>The merger was also a tidy-up.</strong> Merging with AB Tasty did more than add revenue. Everstone bought out AB Tasty&apos;s venture investors and put a single sponsor over both companies, so the combined entity has one clean owner rather than two separate cap tables and competing boards. Clearing the ownership is half of what makes a merger like this workable.<ul className="constraint-list">
<li>In plain terms, a buy-and-build: using one acquired company as a base to buy others, assembling scale by combination rather than growing it organically. The first purchase is the platform; the ones that follow are bolt-ons and mergers that plug into it.</li>
</ul></li>
</ul>
<div className="pull-quote">
<p><strong>Why it matters to you.</strong> Three portable lessons. If you advise a bootstrapped founder weighing an exit: selling a majority for cash while keeping a minority and a board seat takes money off the table without giving up all the upside, and Wingify is the template. If you advise a PE buyer of a founder-led company: continuity is the asset, so keep the management, equity and culture, because the alternative is buying a shell. And if you are building in a consolidating software market: capital changes what is possible, and a well-funded platform assembles in a year what a self-funded one cannot in a decade.</p>
</div>
<h2>Featured Deal</h2>
<h3>The buy-and-build in fast-forward: how a $200M company became a $400M one in twelve months</h3>
<p><em>Real deal, announced January 2025; AB Tasty merger January 2026; rights issue April 2026. Figures from Everstone and Wingify releases, RoC filings, and verified media. Deal value is press-reported and founder-confirmed, not in official filings. Not investment advice.</em></p>
<p><strong>First, what a bootstrapped company will not do</strong></p>
<ul className="constraint-list">
<li>It will not make acquisitions it cannot fund from its own cash, which is why Wingify made none in fifteen years despite reaching $50M of revenue.</li>
<li>It will not run its profits negative to chase growth, because there is no outside investor to cover the gap. Wingify stayed profitable throughout by design.</li>
<li>And it will not take on the integration risk of a cross-border merger, because a self-funded company protects the business it has rather than betting it on a bigger one.</li>
</ul>
<p><strong>The three-part answer</strong></p>
<ul className="constraint-list">
<li><strong>Capital removes the constraint that kept the company cautious.</strong> The single thing a buyout changes is access to money and the willingness to spend it. Everstone could write cheques for Blitzllama and AB Tasty and back a $150M rights issue, because that is what a fund does. The same company, under the same brand, behaves completely differently, not because the business changed but because the balance sheet did.</li>
<li><strong>A platform is worth more than the sum of its parts, if the parts fit.</strong> Wingify at $50M is a niche leader; combined with AB Tasty above $100M, it is a credible challenger to Optimizely and Adobe. The step-up from ~4x revenue for Wingify to ~4-5x on the larger entity is the market pricing in that scale, provided integration delivers. Assembly creates value only when the pieces genuinely combine.</li>
<li><strong>Speed is a strategy, not just a pace.</strong> Everstone did all of this in twelve months, not five years. In a consolidating market the prize goes to whoever builds scale first, because customers and talent gravitate to the largest independent player. Moving fast is how a new entrant becomes the consolidator rather than the consolidated, and the rights issue kept the momentum going.</li>
</ul>
<p><em>The ladder in full: a platform, a bolt-on, a merger and a capital raise, each step adding scale the bootstrapped company could not reach alone. Sources: TechCrunch, Inc42, ET.</em></p>
<div className="pull-quote">
<p><strong>The signal most briefs miss.</strong> The interesting number is not the $200M Everstone paid; it is the $150M it put in fifteen months later. A rights issue at ₹ 8,590 a share, led by the sponsor, is Everstone paying up again, at a higher valuation, to fund the build it started. That second cheque is the real signal of conviction, and it tells you the buyout was never the deal. The buyout was the platform, and the platform is only worth what the sponsor is willing to keep funding. When you see a PE owner inject fresh primary capital soon after buying, read it as the strategy, not a rescue.</p>
</div>
<h2>Sector Signal</h2>
<h3>Three things this deal confirms about Indian SaaS and private equity</h3>
<p><em>India builds software companies of real scale; selling one whole to a fund is still the exception. Sources: TechCrunch, Inc42.</em></p>
<ul className="constraint-list">
<li><strong>Indian SaaS now produces assets big enough for a PE buyout, but full exits stay rare.</strong> India has several $50M-plus software companies, Freshworks, Zoho, Postman, but they mostly list, stay founder-owned, or keep raising venture money. A founder selling the whole thing to private equity for cash is uncommon, which is exactly why this deal drew notice. It is a sign the ecosystem is maturing to the point where clean exits are possible.</li>
<li><strong>Buy-and-build has arrived in Indian software.</strong> Everstone did not buy Wingify to run it as is; it bought a platform to consolidate a global market, adding Blitzllama and AB Tasty within a year. As Indian SaaS matures, the value increasingly comes from combining companies into scaled platforms, not just growing single products, and that favours buyers with capital and a roll-up plan.</li>
<li><strong>The bootstrapped-to-PE handoff is a distinct and repeatable trade.</strong> A profitable, self-funded company is cautious by necessity and valuable because of it: clean, independent, cash-generative. A fund pays for that quality and then removes the caution, funding the growth the founder would not risk. Wingify is a template other bootstrapped Indian SaaS founders and their potential buyers will both study.</li>
</ul>
<p><em>What the price actually buys: a proven product, global reach, and the rarity of a profitable company built without outside money. Sources: Everstone release, TechCrunch.</em></p>
<div className="pull-quote">
<p><em><strong>Signal for advisors:</strong></em> Two conversations this week. Any bootstrapped founder with real revenue and no outside capital: a majority sale for cash, keeping a minority and a board seat, is a live and rare option, and this is the comp. And any client acquiring a founder-led software company: the value is the people and the product, so a plan that keeps management and culture intact is worth more than any cost synergy you could model.</p>
</div>
<h2>Valuation Pulse</h2>
<h3>Was ~4x revenue right for a profitable SaaS company? Three ways to judge it</h3>
<div className="deal-table-wrap">
<table className="deal-table">
<thead><tr><th><strong>Way to measure it</strong></th><th><strong>What it says here</strong></th></tr></thead>
<tbody>
<tr><td><strong>Price against revenue</strong></td><td>About 4x the $50M ARR, which is modest for software: high-growth SaaS often changes hands at double-digit revenue multiples. The discount reflects that Wingify was profitable and steadily growing rather than hyper-growth, and that a bootstrapped founder wanted a clean cash exit.</td></tr>
<tr><td><strong>Price against the platform it became</strong></td><td>The combined entity is valued at $400–500M, roughly 4–5x its larger revenue base. The multiple held even as the business tripled in scale, so the value created came from adding revenue at a similar multiple, not from re-rating. Assembly, not arbitrage.</td></tr>
<tr><td><strong>Price against building it</strong></td><td>Fifteen years to reach $50M of profitable revenue and 6,000 clients across 90 countries, with no outside capital, is almost impossible to replicate. Everstone paid a low multiple for a business whose real scarcity is that it was built at all, profitably, without funding.</td></tr>
</tbody>
</table>
</div>
<p><em>The cost of the growth push: revenue up 34%, profit down 60%, expenses up 70%, all by design in the first year of PE ownership. Sources: Wingify annual filing.</em></p>
<ul className="constraint-list">
<li>What &apos;4x revenue&apos; means: the price is about four times a year&apos;s sales. For profitable, moderate-growth software that is a reasonable multiple; the market pays far more for faster growth, which is precisely what Everstone is now spending to manufacture.</li>
</ul>
<p><strong>The discipline.</strong> Judge this on the platform, not the entry multiple. About 4x revenue for a profitable SaaS asset is fair on its own, but the thesis is that Everstone can build something worth far more by combining it with others. FY25 shows the cost: profit down 60% as expenses rose 70%, a deliberate trade of margin for growth that only pays off if the combined entity keeps scaling toward the Optimizely tier. The deal value everyone quotes is press-reported, not filed, and the combined valuation is a private mark, so treat both as directional. The real test is whether $100M of assembled revenue becomes $200M.</p>
<div className="pull-quote">
<p><strong>This issue.</strong> Watch three things. The integration: two product stacks, ~800 people and 11 offices across Delhi and Paris have to become one company, and both products are still running in parallel. The margin: FY25 profit fell 60% on purpose, so the question is whether the growth it bought shows up in FY26, the first full year of combined ownership. And the concentration: ~90% of revenue comes from the US and Europe, so any enterprise-budget squeeze in those markets hits the whole platform at once.</p>
</div>
<h2>Deal Structure Clinic</h2>
<h3>The founder buyout, and why keeping the seller in is the point</h3>
<p><strong>In plain terms, a management buyout with a sponsor:</strong> A private-equity firm buys most of a company but leaves the operating team holding meaningful equity, so the people who run it stay invested in it. The fund provides capital and ambition; management provides continuity and the knowledge that built the business.</p>
<p><strong>In plain terms, why a partial exit beats a full one:</strong> If the founder sold 100% and left, the institutional knowledge and culture would leave too. By selling 80% and keeping 10.45% plus a board seat, the founder banks liquidity while staying aligned with the outcome, and the buyer keeps the asset intact.</p>
<p><strong>Three mechanics this deal showcases</strong></p>
<p><em>The AB Tasty merger doubled as a cap-table cleanup: two venture funds out, one sponsor over both companies. Sources: ScanX, TechCrunch.</em></p>
<ul className="constraint-list">
<li><strong>Buying most, not all, keeps the people invested.</strong> Everstone took 80% but left the CEO and leadership with real equity, so their incentive to build the combined company is genuine, not contractual. When a business&apos;s value lives in its people, structure the deal so those people still own a piece of the upside. A fully bought-out team is a hired team; a partly-owning team is a committed one.</li>
<li><strong>A merger is a chance to clean the cap table.</strong> Everstone did not just combine Wingify and AB Tasty; it bought out AB Tasty&apos;s old venture backers, leaving a single sponsor over both. Consolidating ownership at the moment of a merger avoids years of misaligned investors and competing boards. Use the combination to simplify who owns what, not just what the company sells.</li>
<li><strong>Fresh primary capital signals where the plan is going.</strong> The $150M rights issue put new money into the company, not into selling shareholders&apos; pockets, and Everstone led it. Primary capital funds the build; secondary capital funds an exit. When a sponsor leads a primary raise soon after buying, it is committing to the growth plan, and the size of that cheque is the measure of its conviction.</li>
</ul>
<h2>M&amp;A 101</h2>
<h3>Turning a niche leader into a platform: the three-step playbook</h3>
<p><strong>In plain terms, a platform strategy:</strong> Buying a solid company not to run it unchanged, but to use it as the base for acquiring others and building scale. The first deal supplies the product, the customers and the team; the return is expected to come from what gets built on top of it.</p>
<p><strong>The three steps, using this deal</strong></p>
<ul className="constraint-list">
<li><strong>Step 1: Buy the base for its quality, not its growth rate.</strong> A good platform is profitable, well-run and trusted by customers, even if not growing explosively. Wingify was exactly that: $50M of profitable revenue, 6,000 clients, a clean fifteen-year record. Buy the durable, well-built asset, because you can add growth with capital but not quality.</li>
<li><strong>Step 2: Add scale by combination, and fund it deliberately.</strong> Once you own the base, grow it by acquiring what fits: Blitzllama for capability, AB Tasty for scale and geography. Each addition has to plug into the platform rather than sit beside it, and be paid for, which is why the $150M rights issue came alongside the deals. Assembly needs both a plan and a cheque book.</li>
<li><strong>Step 3: Keep the operators aligned and the ownership clean.</strong> A platform only works if the people running it want to build it, so leave management with equity, and simplify ownership as you go rather than accumulating investors and boards. Everstone kept the CEO invested and used the merger to clear AB Tasty&apos;s old backers. The cleaner the alignment, the faster the platform can move.</li>
</ul>
<p><em>The assembled result: over $100M of revenue, 4,000 customers and a seat at the table with Optimizely and Adobe. Sources: Wingify release, Inc42, ProductGrowth.</em></p>
<div className="pull-quote">
<p><strong>Read this before you build a platform by acquisition.</strong> Three things decide whether it works: whether the base you bought is durable enough to build on, whether each addition genuinely combines rather than merely adds, and whether you keep the operators invested and the ownership clean as you go. Everstone bought a fifteen-year-old profitable base, combined it with a real peer, and funded the build with fresh primary capital it led itself. The platform is assembled; whether it becomes a category winner depends on integration Everstone has only just begun. Not investment advice.</p>
</div>
<h2>Live Mandate</h2>
<h3>ACTIVE BUYER BRIEF · KPE-2026-001 · REPLY TO REFER</h3>
<p><strong>We are looking for a textile manufacturing business in Maharashtra or Gujarat.</strong></p>
<div className="deal-table-wrap">
<table className="deal-table">
<thead><tr><th><strong>Field</strong></th><th><strong>Detail</strong></th></tr></thead>
<tbody>
<tr><td><strong>Sector</strong></td><td>Textile manufacturing: yarn, fabric, garments, or processing units</td></tr>
<tr><td><strong>Deal type</strong></td><td>Full acquisition or majority stake</td></tr>
<tr><td><strong>Geography</strong></td><td>Maharashtra and Gujarat</td></tr>
<tr><td><strong>Revenue</strong></td><td>₹ 1 Cr to ₹ 25 Cr. At least 20% operating margin. Revenue discussed privately after the first fit check.</td></tr>
<tr><td><strong>Exclusions</strong></td><td>No D2C brands. No consumer retail or e-commerce.</td></tr>
<tr><td><strong>How to refer</strong></td><td>WhatsApp the CA Ambassador Group or email <a href="mailto:hello@kautilya-pe.com" target="_blank" rel="noopener noreferrer">hello@kautilya-pe.com</a>. A short message is enough. No formal report needed.</td></tr>
</tbody>
</table>
</div>

<div className="blog-faq">
<div className="phase-label" style={{ marginBottom: 20 }}>Frequently Asked Questions</div>
<div className="blog-faq-item">
<div className="blog-faq-q">How much did Everstone pay for Wingify?</div>
<p className="blog-faq-a">Everstone paid roughly $200M, all cash, for 80% of Wingify, about four times the $50M of annual recurring revenue. The figure is press-reported and confirmed by the founder, not in official filings.</p>
</div>
<div className="blog-faq-item">
<div className="blog-faq-q">Who owns Wingify after the deal?</div>
<p className="blog-faq-a">After dilution, per the March 2025 RoC filing, Everstone holds 76.84%, founder Paras Chopra 10.45%, Vyom Mankekar 5.07% and CEO Sparsh Gupta 4.86%. Chopra also kept a board seat but has no operating role.</p>
</div>
<div className="blog-faq-item">
<div className="blog-faq-q">What did Everstone do with Wingify after buying it?</div>
<p className="blog-faq-a">In December 2025 Wingify acquired Blitzllama, an AI user-research startup and its first acquisition. In January 2026 it merged with AB Tasty of Paris to pass $100M of combined revenue. In April 2026 a ₹ 1,381 Cr ($150M) rights issue led by Everstone funded the build.</p>
</div>
<div className="blog-faq-item">
<div className="blog-faq-q">What is a buy-and-build or platform strategy?</div>
<p className="blog-faq-a">It means buying a solid company not to run it unchanged, but to use it as the base for acquiring others and building scale. The first deal supplies the product, the customers and the team; the return is expected to come from what gets built on top of it.</p>
</div>
<div className="blog-faq-item">
<div className="blog-faq-q">Why does the $150M rights issue matter?</div>
<p className="blog-faq-a">It put new money into the company rather than into selling shareholders&apos; pockets, and Everstone led it at ₹ 8,590 a share. Primary capital funds the build, so a sponsor leading a primary raise soon after buying is committing to the growth plan.</p>
</div>
</div>

<div className="sources-appendix">
<div className="phase-label" style={{ marginBottom: 20 }}>Sources &amp; Method</div>

<p>Sources: Everstone Capital release via BusinessWire (Jan 24, 2025) · VWO release (Jan 24, 2025) · RoC filing via Entrackr (Apr 2026) · Wingify FY25 annual filing · TechCrunch (Jan 2025, Jan 2026) · Inc42 · Entrackr · YourStory · ScanX · CBInsights · ProductGrowth. Dollar figures at the announcement-day rate (~₹ 86.5 to the dollar). The ~$200M deal value is press-reported and founder-confirmed, not company-disclosed; the AB Tasty merger value of $400–500M is press-reported; the ~4x revenue multiple is derived. Both the deal and merger values are for unlisted entities and unlikely to be formally filed.</p>

<p>The India Deal Sheet is published every Wednesday and Saturday, and past teardowns are collected in the <Link href="/newsletter">Kautilya Newsletter</Link>. Analysis is for informational purposes. Not investment advice.</p>
</div>

        <div className="story-coda">
<p className="coda-text">Ready to start a conversation? 20 minutes. One call. No commitment.</p>
          <Link href="/newsletter" className="coda-link">Read More Teardowns</Link>
          <a href="https://kautilya-pe.beehiiv.com" target="_blank" rel="noopener noreferrer" className="coda-link secondary">Subscribe on Beehiiv</a>
        </div>
      </article>
    </>
  );
}
